name: CI/CD - Build & Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME,, }}/fastapi-ml-app:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME,, }}/fastapi-ml-app:latest
