name: CI/CD - FastAPI with Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Build Docker image
        run: docker build -t fastapi-ml-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name fastapi-ml-app fastapi-ml-app
          sleep 10   # wait for app to start

      - name: Test FastAPI in container
        run: |
          curl -X POST "http://localhost:8000/predict" \
            -H "Content-Type: application/json" \
            -d '{"features":[5.1,3.5,1.4,0.2]}'
